### POST request to example server
POST localhost:8080/query/1?query=123&value=12345
Content-Type: application/json

{"name": "John Doe"}

### GET request to example server
GET localhost:8080/query/2?query=123


### GET request to example server
GET localhost:8080/query/2?query=123&value=12345&test_int_slice=1&test_int_slice=2&test_int_slice=3


### GET request to example server
GET localhost:8080/query/2?query=123&value=12345&test_int_slice=1&test_int_slice=2&test_int_slice=abc

### GET request to example server
GET localhost:8080/query/2?query=123&value=12345&teststruct.field1=123&teststruct.field2=hello